name: CD

trigger:
  branches:
    include:
      - main
      - master
      - releases/*
      - refs/tags/v*
      
pr:
- main
- releases/*

jobs:
  - job: Windows
    pool:
      vmImage: 'windows-2022'
    steps:
      - script: |
        pip install conan
        conan config install https://github.com/ultimaker/conan-config.git
        conan profile new default --detect
        conan user -p ${env:CONAN_PASS} -r ultimaker ${env:CONAN_USER}
      displayName: prepare Conan
    - script: conan create . ultimaker/testing -pr:b cura_build.jinja -pr:h cura_release.jinja --build=missing
      displayName: create package
      - script: conan upload "* -r ultimaker --all -c
        displayName: upload package
  - job: macOS
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - script: |
          pip3 install conan
        conan config install https://github.com/ultimaker/conan-config.git
        conan profile new default --detect
        conan user -p $(CONAN_PASS) -r ultimaker $(CONAN_USER)
      displayName: prepare Conan
      - script: conan create . ultimaker/testing -pr:b cura_build.jinja -pr:h cura_release.jinja --build=missing
        displayName: create package
          - script: conan upload "*" -r ultimaker --all -c
            displayName: upload package
  - job: Linux
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - script: |
        pip install conan
        conan config install https://github.com/ultimaker/conan-config.git
        conan profile new default --detect
        conan user -p $(CONAN_PASS) -r ultimaker $(CONAN_USER)
      displayName: prepare Conan
    - script: conan create . ultimaker/testing -pr:b cura_build.jinja -pr:h cura_release.jinja --build=missing
      displayName: create package
        - script: conan upload "*" -r ultimaker --all -c
          displayName: upload package
